apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    course: kubernetes
spec:
  containers:
  - name: first-pod
    image: nginx
    ports:
    - containerPort: 80
  - name: second-pod
    image: ubuntu
    command:
      - /bin/bash
      - -ec
      - while true; do echo $(date); sleep 10; done
