apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webserver
  name: example-pod1
spec:
  containers:
  - image: nginx
    name: example-pod1-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
