apiVersion: v1
kind: Pod
metadata:
  labels:
    course: devops
  name: nginx-with-port
spec:
  containers:
  - image: nginx
    name: nginx-with-port
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
